### ISSUE TITLE
CPUID-Interception minor problem

### ISSUE THREAD

**Issue by Zero-Tang** [tandasat/SimpleSvmHook#4]
https://github.com/tandasat/SimpleSvmHook/blob/7cef39ffad9c15a31615a9b032b910011b3bdb1b/SimpleSvmHook/VmmMain.cpp#L85
The problem is minor that highest bit was mistakenly set on edx. It is supposed to be placed on ecx register. You might want to fix your "SimpleSvm" repository as well: https://github.com/tandasat/SimpleSvm/blob/457259cf864937c0932b7482d696f5c1264d454b/SimpleSvm/SimpleSvm.cpp#L508
It should be corrected as `registers[2] |= CPUID_FN0000_0001_ECX_HYPERVISOR_PRESENT;`

**Comment by tandasat** [comment]
Fixed both projects. Thank you for reporting this. Programming is hard!
