### ISSUE TITLE
SYSTEM_THREAD_EXCEPTION_NOT_HANDLED Win10 20H2 Ryzen5 3600

### ISSUE THREAD

**Issue by WolfyZ99** [tandasat/SimpleSvmHook#6]
Just tried to run the driver with no modifications at all and got BSOD. According to log file it stops at "Start virtualizing the all processors."

> SYSTEM_THREAD_EXCEPTION_NOT_HANDLED_M (1000007e)
This is a very common bugcheck.  Usually the exception address pinpoints
the driver/function that caused the problem.  Always note this address
as well as the link date of the driver/image that contains this address.
Some common problems are exception code 0x80000003.  This means a hard
coded breakpoint or assertion was hit, but this system was booted
/NODEBUG.  This is not supposed to happen as developers should never have
hardcoded breakpoints in retail code, but ...
If this happens, make sure a debugger gets connected, and the
system is booted /DEBUG.  This will let us see why this breakpoint is
happening.
Arguments:
Arg1: ffffffffc0000005, The exception code that was not handled
Arg2: fffff804174112cb, The address that the exception occurred at
Arg3: fffffe0aaa85a338, Exception Record Address
Arg4: fffffe0aaa859b70, Context Record Address
Debugging Details:
WARNING: Unable to verify timestamp for SimpleSvmHook.sys
WARNING: Unable to verify checksum for win32k.sys
KEY_VALUES_STRING: 1
    Key  : AV.Dereference
    Value: NullPtr
    Key  : AV.Fault
    Value: Read
    Key  : Analysis.CPU.mSec
    Value: 4780
    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on DESKTOP-5RJB31R
    Key  : Analysis.DebugData
    Value: CreateObject
    Key  : Analysis.DebugModel
    Value: CreateObject
    Key  : Analysis.Elapsed.mSec
    Value: 27611
    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 83
    Key  : Analysis.System
    Value: CreateObject
    Key  : WER.OS.Branch
    Value: vb_release
    Key  : WER.OS.Timestamp
    Value: 2019-12-06T14:06:00Z
    Key  : WER.OS.Version
    Value: 10.0.19041.1
ADDITIONAL_XML: 1
OS_BUILD_LAYERS: 1
BUGCHECK_CODE:  7e
BUGCHECK_P1: ffffffffc0000005
BUGCHECK_P2: fffff804174112cb
BUGCHECK_P3: fffffe0aaa85a338
BUGCHECK_P4: fffffe0aaa859b70
EXCEPTION_RECORD:  fffffe0aaa85a338 -- (.exr 0xfffffe0aaa85a338)
ExceptionAddress: fffff804174112cb (SimpleSvmHook+0x00000000000012cb)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000000
Attempt to read from address 0000000000000000
CONTEXT:  fffffe0aaa859b70 -- (.cxr 0xfffffe0aaa859b70)
rax=0000000000000000 rbx=0000000000001000 rcx=0000000000000000
rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000000
rip=fffff804174112cb rsp=fffffe0aaa85a570 rbp=000ffffffffff000
 r8=ffffd70000000000  r9=0000007ffffffff8 r10=0000000000000001
r11=ffffd76bb5dae000 r12=ffffc701f98c9fec r13=ffffc701f98c9e50
r14=ffffc701f80ff000 r15=ffffc701f5e023a0
iopl=0         nv up ei pl zr na po nc
cs=0010  ss=0000  ds=002b  es=002b  fs=0053  gs=002b             efl=00050246
SimpleSvmHook+0x12cb:
fffff804`174112cb f604c801        test    byte ptr [rax+rcx*8],1 ds:002b:00000000`00000000=??
Resetting default scope
BLACKBOXBSD: 1 (!blackboxbsd)
BLACKBOXNTFS: 1 (!blackboxntfs)
BLACKBOXPNP: 1 (!blackboxpnp)
BLACKBOXWINLOGON: 1
CUSTOMER_CRASH_COUNT:  1
PROCESS_NAME:  System
READ_ADDRESS: fffff8040a4fb390: Unable to get MiVisibleState
Unable to get NonPagedPoolStart
Unable to get NonPagedPoolEnd
Unable to get PagedPoolStart
Unable to get PagedPoolEnd
fffff8040a40f340: Unable to get Flags value from nt!KdVersionBlock
fffff8040a40f340: Unable to get Flags value from nt!KdVersionBlock
unable to get nt!MmSpecialPagesInUse
 0000000000000000 
ERROR_CODE: (NTSTATUS) 0xc0000005 -                      0x%p                               0x%p.                      %s.
EXCEPTION_CODE_STR:  c0000005
EXCEPTION_PARAMETER1:  0000000000000000
EXCEPTION_PARAMETER2:  0000000000000000
EXCEPTION_STR:  0xc0000005
STACK_TEXT:  
fffffe0a`aa85a570 00000000`00001000     : 00000000`4d565353 ffffc701`00000000 00000000`00000000 ffffc701`f5e023a0 : SimpleSvmHook+0x12cb
fffffe0a`aa85a578 00000000`4d565353     : ffffc701`00000000 00000000`00000000 ffffc701`f5e023a0 fffffe0a`aa85a760 : 0x1000
fffffe0a`aa85a580 ffffc701`00000000     : 00000000`00000000 ffffc701`f5e023a0 fffffe0a`aa85a760 00000000`00000001 : 0x4d565353
fffffe0a`aa85a588 00000000`00000000     : ffffc701`f5e023a0 fffffe0a`aa85a760 00000000`00000001 fffff804`17411ab3 : 0xffffc701`00000000
SYMBOL_NAME:  SimpleSvmHook+12cb
MODULE_NAME: SimpleSvmHook
IMAGE_NAME:  SimpleSvmHook.sys
STACK_COMMAND:  .cxr 0xfffffe0aaa859b70 ; kb
BUCKET_ID_FUNC_OFFSET:  12cb
FAILURE_BUCKET_ID:  AV_SimpleSvmHook!unknown_function
OS_VERSION:  10.0.19041.1
BUILDLAB_STR:  vb_release
OSPLATFORM_TYPE:  x64
OSNAME:  Windows 10
FAILURE_ID_HASH:  {6486c827-0461-632e-3e20-f9875ce0c768}
Followup:     MachineOwner

**Comment by tandasat** [comment]
Can load the symbol and post the output of `!analyze -v` ? It does not look the symbol was applied.

**Comment by ghost** [comment]
`fffff804174112cb f604c801 test byte ptr [rax+rcx*8],1 ds:002b:0000000000000000=??
`

This is where you are crashing, it helps to load the source file or load the binary into a decompiler to determine where you are accessing invalid address.

**Comment by ghost** [comment]
I tested simplesvmhook today and I got a similar bugcheck, and it was because the NPT entries weren't zero-initialized, which caused random present bits to be set in NPT entries, which tricks the code into thinking there is a valid NPT table referenced, leading to an access violation BSOD. I suggest that you use ExAllocatePoolZero for creating NPT tables.


**Unrelated**: I am trying to figure out how to start this from a system thread, is calling VirtualizeAllProcessors from PsCreateSystemThread safe? I'm having some other access violation issue in PspTerminateThreadByPointer, as soon as the thread ends.  (**EDIT**: Using PsTerminateThread rather than normally returning worked for me)

**Comment by tandasat** [comment]
Thanks for sharing the findings. I encourage you to submit a PR so others can benefit. At glance, I was not able to spot where zero initialization is lacking.

On the other topic, I would suppose it would be safe, but obviously you found otherwise. Happy debugging!

**Comment by tandasat** [comment]
I believe this is the same issue as #7, which caused null pointer access bug check with the same log entries. The problem was a recent-ish change in NT's memory allocation API.

If you still see the same problem with the latest commit, please reopen this.
