### ISSUE TITLE
Access violation issue

### ISSUE THREAD

**Issue by ghost** [tandasat/SimpleSvmHook#7]
Hello, I just downloaded the repository and loaded it with OSR loader normally. I'm getting this strange access violation issue. 

My CPU specs: 
![image](https://user-images.githubusercontent.com/77312921/108140083-373b0a00-7076-11eb-860b-6337f25ecf05.png)

**Crash info:** 
[simplesvmhook_issue.txt](https://github.com/tandasat/SimpleSvmHook/files/5992480/simplesvmhook_issue.txt)

**Comment by tandasat** [comment]
@NickTsl I was able to reproduce the issues and fix it. Please try the latest revision and let me know if the issue still persists. Thank you for reporting this.
