### ISSUE TITLE
Hello, my senior

### ISSUE THREAD

**Issue by progromyang** [tandasat/SimpleSvmHook#8]
Hello, my senior, after reading the NPT part of your simplesvmhook source code, I found that memory hiding is different from Intel's EPT. Intel uses read bit to partition. I checked the AMD manual and found that read bit cannot be set to control read. You added NPT when dealing with NPT_ Is the state ntpstate structure increased because amd has no read bit?

**Comment by tandasat** [comment]
It is correct that complexity you see is due to the lack of the readable bit.

Please read README.md for more details.
```
NPT, the AMD implementation of SLAT, does not permit a hypervisor to 
configure the permission as execute-only because there is no bit to indicate 
whether the page is readable. To make the page executable, it must also be 
readable at the same time. This limitation requires significant changes in a 
way to hide hooks.
```

**Comment by progromyang** [comment]
Thank you for your reply.

It's right for you to make major changes on the hook page!!

In your simplesvmhook source code, I try to dynamically add hook pages to create a blue screen. I hope you can give me some advice,



The code is as follows:

VOID InitProcessGamePage(PVIRTUAL_PROCESSOR_DATA VpData, PHOOK_GAME_ENTRY initPage)

{

ULONG_ PTR KernelCr3,CurrentCr3;

CurrentCr3 = __ readcr3();



KernelCr3=VmmpGetKernelCr3(VpData->GuestVmcb.StateSaveArea.Cr3);

//Switch CR3 to kernel CR3

__ writecr3(KernelCr3);

if (VpData->HookData->NptState == NptHookEnabledVisible)

{

KdPrint(("initProcess NptState 2\r\n"));

TransitionNtpState2To1(VpData->HookData);

}

else if(VpData->HookData->NptState==NptHookEnabledInvisible)

{

ChangePermissionOfPage(VpData->HookData->Pml4Table,

initPage->Hook_ Entry. PhyPageBase,

TRUE);

}



__ writecr3(CurrentCr3);
